import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppHeader, StatusBadge, SurfaceCard, VisualBottomNav } from '../components/VisualPrimitives';
import { colors } from '../theme/tokens';

export function ZoneDetailsScreen() {
  return <SafeAreaView style={styles.safeArea}><View style={styles.page}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <AppHeader title="Zone Details" subtitle="SZ-A03" avatarLabel="JC" />
    <View style={styles.hero}><View style={styles.zoneIcon}><Text style={styles.zoneIconText}>▱</Text></View><Text style={styles.title}>Assembly Line 3</Text><Text style={styles.location}>Production Hall · East Wing</Text><StatusBadge label="ACCESS PERMITTED" tone="success" /></View>
    <SurfaceCard><Text style={styles.cardTitle}>Your access</Text><View style={styles.infoGrid}><View style={styles.info}><Text style={styles.label}>ACCESS WINDOW</Text><Text style={styles.value}>06:00–18:00</Text></View><View style={styles.info}><Text style={styles.label}>CURRENT SHIFT</Text><Text style={styles.value}>Day shift</Text></View><View style={styles.info}><Text style={styles.label}>POLICY</Text><Text style={styles.value}>Maintenance staff</Text></View><View style={styles.info}><Text style={styles.label}>STATUS</Text><Text style={styles.successValue}>Active</Text></View></View></SurfaceCard>
    <SurfaceCard tone="info"><Text style={styles.cardTitle}>Safety requirements</Text><View style={styles.requirement}><View style={styles.check}><Text style={styles.checkText}>✓</Text></View><View><Text style={styles.requirementTitle}>Personal protective equipment</Text><Text style={styles.requirementDetail}>Helmet, safety glasses and protective footwear</Text></View></View><View style={styles.requirement}><View style={styles.check}><Text style={styles.checkText}>✓</Text></View><View><Text style={styles.requirementTitle}>Safety briefing</Text><Text style={styles.requirementDetail}>Completed · Valid until December 2026</Text></View></View></SurfaceCard>
    <Text style={styles.sectionTitle}>Zone information</Text><View style={styles.mapMock}><View style={styles.mapGrid}>{Array.from({length:18},(_,i)=><View key={i} style={styles.mapCell}/>)}</View><View style={styles.mapPin}><Text style={styles.mapPinText}>⌖</Text></View><View style={styles.mapCaption}><Text style={styles.mapCaptionTitle}>East Wing · Level 1</Text><Text style={styles.mapCaptionDetail}>Nearest entrance: East Gate</Text></View></View>
    <View style={styles.contactCard}><View style={styles.contactIcon}><Text style={styles.contactIconText}>i</Text></View><View style={styles.contactCopy}><Text style={styles.contactTitle}>Zone supervisor</Text><Text style={styles.contactDetail}>Anna Mitchell · Production Manager</Text></View><Text style={styles.contactAction}>Contact</Text></View>
  </ScrollView><VisualBottomNav items={[{icon:'⌂',label:'Home'},{icon:'▦',label:'My QR'},{icon:'✓',label:'Access'},{icon:'○',label:'Profile'}]} selected="Access" /></View></SafeAreaView>;
}
const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:colors.background},page:{width:'100%',maxWidth:480,flex:1,alignSelf:'center'},content:{padding:20,gap:16,paddingBottom:28},hero:{alignItems:'center',padding:20,borderWidth:1,borderColor:'#CBE8DA',borderRadius:19,backgroundColor:'#F8FDFB'},zoneIcon:{width:58,height:58,alignItems:'center',justifyContent:'center',marginBottom:10,borderRadius:18,backgroundColor:colors.successSoft},zoneIconText:{color:colors.success,fontSize:30,fontWeight:'900'},title:{color:colors.text,fontSize:21,fontWeight:'900'},location:{marginTop:4,marginBottom:10,color:colors.textMuted,fontSize:11},cardTitle:{marginBottom:14,color:colors.text,fontSize:15,fontWeight:'900'},infoGrid:{flexDirection:'row',flexWrap:'wrap',rowGap:16},info:{width:'50%'},label:{color:colors.textMuted,fontSize:8,fontWeight:'900',letterSpacing:.6},value:{marginTop:5,color:colors.text,fontSize:11,fontWeight:'700'},successValue:{marginTop:5,color:colors.success,fontSize:11,fontWeight:'800'},requirement:{flexDirection:'row',alignItems:'center',marginBottom:13},check:{width:29,height:29,alignItems:'center',justifyContent:'center',marginRight:10,borderRadius:10,backgroundColor:colors.successSoft},checkText:{color:colors.success,fontWeight:'900'},requirementTitle:{color:colors.text,fontSize:11,fontWeight:'800'},requirementDetail:{marginTop:3,color:colors.textMuted,fontSize:8},sectionTitle:{color:colors.text,fontSize:15,fontWeight:'900'},mapMock:{height:190,overflow:'hidden',borderWidth:1,borderColor:colors.border,borderRadius:18,backgroundColor:'#E9EEF4'},mapGrid:{flex:1,flexDirection:'row',flexWrap:'wrap'},mapCell:{width:'33.33%',height:'33.33%',borderWidth:.5,borderColor:'#D5DDE6'},mapPin:{position:'absolute',top:55,left:'43%',width:45,height:45,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:colors.surface,borderRadius:23,backgroundColor:colors.primary},mapPinText:{color:colors.surface,fontSize:22},mapCaption:{position:'absolute',left:10,right:10,bottom:10,padding:10,borderRadius:11,backgroundColor:'rgba(255,255,255,.94)'},mapCaptionTitle:{color:colors.text,fontSize:11,fontWeight:'900'},mapCaptionDetail:{marginTop:3,color:colors.textMuted,fontSize:8},contactCard:{flexDirection:'row',alignItems:'center',padding:14,borderWidth:1,borderColor:colors.border,borderRadius:16,backgroundColor:colors.surface},contactIcon:{width:35,height:35,alignItems:'center',justifyContent:'center',borderRadius:11,backgroundColor:colors.primarySoft},contactIconText:{color:colors.primary,fontSize:17,fontWeight:'900'},contactCopy:{flex:1,marginLeft:10},contactTitle:{color:colors.text,fontSize:11,fontWeight:'900'},contactDetail:{marginTop:3,color:colors.textMuted,fontSize:8},contactAction:{color:colors.primary,fontSize:9,fontWeight:'900'}});
